---
name: Ansible for Network Automation
slug: ansible-network-automation
category: tools
diagram: "https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/master/lessons/ansible-network-automation/diagram.png"
tier: prod
prereqs:
  # - python-intro  #not available yet
  - linux-basics
description: In this lesson, we'll explore the use of Ansible for multi-vendor network automation
shortDescription: Ansible
tags:
- ansible
- automation
- configuration
collection: red-hat

authors:
- name: Red Hat
  link: https://ansible.com

endpoints:
- name: ansible
  image: ansible
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx1
  image: vqfx-snap1
  configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh
  additionalPorts: [830]

- name: cvx1
  image: cvx
  configurationType: python
  presentations:
  - name: cli
    port: 22
    type: ssh

connections:
- a: vqfx1
  b: cvx1

stages:
  - description: Enable NETCONF
    guideType: markdown
  - description: Facts
    guideType: markdown
  - description: Resource Facts
    guideType: markdown
  - description: Network Configuration Templates
    guideType: markdown
