---
name: Device Specific Template Generation
slug: template-generation-device
diagram: https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/v0.3.2/lessons/lesson-35/lessondiagram.png
category: workflows
tier: prod
prereqs:
  - linux-basics
  - yaml-introduction
  - jinja-configuration-templates
description: Having the ability to generate device specific configurations from an approved device template can be beneficial especially for new deployments. 
shortDescription: Template Generation
tags:
- pyez
- yaml
- jinja2

authors:
- name: Mark Yeates
  link: https://github.com/mayeates
- name: John Weidley
  link: https://github.com/jweidley

endpoints:

- name: linux
  image: utility
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx1
  image: vqfx-snap1
  configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh
  additionalPorts: [830]

- name: vqfx2
  image: vqfx-snap2
  configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh
  additionalPorts: [830]

stages:
  - description: Skills Review
    guideType: markdown
  - description: Multiple Devices
    guideType: markdown
  - description: Multiple Devices w/ Uplinks
    guideType: markdown
  - description: Push Generated Configs to Device
    guideType: markdown
