---
name: Juniper Extension Toolkit (JET)
slug: jet-extending-junos
category: tools
description: "In this lesson, we'll explore the Juniper Extension Toolkit (JET), which is a powerful set of tools for building applications that work with Junos."
tier: ptr
shortDescription: JET
collection: juniper-networks

authors:
- name: Tony Chan
  link: https://github.com/valjeanchan
- name: Raymond Lam
  link: https://github.com/jnpr-raylam

endpoints:

- name: linux
  image: utility
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx
  image: container-vqfx
  configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh
  additionalPorts: [830, 1883, 32767]

connections:
- a: vqfx
  b: linux

stages:
  - description: JET RPC/Notification Configuration
    guideType: markdown

  - description: Receive Events from Notification Service using MQTT client
    guideType: markdown

  - description: IDL Compilation and Basic GRPC JET Testing
    guideType: markdown

  - description: JET Firewall API to Create/Update Firewall Filter
    guideType: markdown

  - description: Closed Loop Automation with JET
    guideType: markdown
