---
name: Network Automation with Salt
slug: salt-network-automation
category: tools
diagram: https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/v0.3.2/lessons/lesson-30/salt.png
tier: prod
prereqs:
  # - python-introduction
  - linux-basics
description: Salt is a powerful automation platform, and is one of the most popular choices in the world of network automation. We'll cover the basics of Salt in this lesson, and explore how to interact with our network devices using this framework.
shortDescription: Salt
tags:
- event driven automation
- network automation
- salt
- saltstack

authors:
- name: Sudhishna Sendhilvelan
  link: https://github.com/Sudhishna
- name: Vinayak Iyer
  link: https://github.com/vinayak-skywalker

endpoints:

- name: salt1
  image: salt
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: vqfx1
  image: vqfx-snap1
  configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh
  additionalPorts: [8080, 830]

connections:
- a: vqfx1
  b: salt1

stages:
  - description: Salt Master and Minion
    guideType: markdown

  - description: Junos Proxy Minions
    guideType: markdown

  - description: Executing Junos commands in Salt
    guideType: markdown

  - description: Junos Configuration Management with Salt
    guideType: markdown
