---
name: Network Unit Testing with JSNAPy
slug: jsnapy-network-testing
category: tools
diagram: https://raw.githubusercontent.com/nre-learning/nrelabs-curriculum/master/lessons/jsnapy-network-testing/jsnapy-crpd.png
tier: prod
prereqs:
  - yaml-introduction
  - linux-basics
description: Unit testing your network devices is one of the fundamental building blocks to CI/CD for networking. In this lesson, we'll explore the use of an open source tool - JSNAPy - for doing just this with Junos devices.
shortDescription: JSNAPy
tags:
- jsnapy
- test
- unit test
- testing
collection: juniper-networks

authors:
- name: Matt Oswalt
  link: https://oswalt.dev

endpoints:
- name: linux
  image: utility
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: r1
  image: crpd
  configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: r2
  image: crpd
  configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh

- name: r3
  image: crpd
  configurationType: napalm
  presentations:
  - name: cli
    port: 22
    type: ssh

connections:
- a: r1
  b: r2
  subnet: 10.12.0.0/24
- a: r2
  b: r3
  subnet: 10.23.0.0/24
- a: r3
  b: r1
  subnet: 10.31.0.0/24

stages:
  - description: Introduction to JSNAPy
    guideType: markdown

  # Planned stages:
  #
  # 0. (done) Quick overview of snapshots and tests. Basic example that gets you to something useful.
  # 1. Deeper-dive into retrieving data. The various ways you can do this (RPC, CLI) (not everything has a dedicated RPC, but everything in Junos is XML. Also state vs config?
  #
  #     - config, or command-line options? do we need a config file for even simple snapshots?
  #
  # 2. Deeper-drive into tests. All of the operators, etc.
  #
  #     - xpath to show a specific node? And then make an assertion about that? Like ensuring that specific OSPF neighbors are present.
  #
  # 3. Using JSNAPy with Python
  # 4. Misc JSNAPy features like sqlite, email, etc? (this one is tentative, depends on if this is interesting after the first four)
